### ISSUE TITLE
Please fix the license

### ISSUE THREAD

**Issue by lu-zero** [cableguard/altuntun#1]
The readme is mentioning GPL-2, while the codebase is BSD-3. It should be clarified.

If we all agree on the license I can try to write down the [REUSE](https://reuse.software/) bits so it is even machine-clear.

**Comment by cableguard** [comment]
@lu-zero I would like to make it all BSD-3 for compatibility with the other wireguard implementations (Go, etc) but as Cloudflare released Boringtun as GPL-2, I can´t. I will clarify it is all GPL-2 to solve the discrepancy.

**Comment by ghost** [comment]
@lu-zero I fixed it, thanks for pointing that out.
